name: Release

on:
  push:
    branches:
      - develop

env:
  TOKEN: ${{ secrets.G_TOKEN }}

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Configure Github Properties
        run: |
          touch ./github.properties
          echo gpr.key="$TOKEN" >> ./github.properties

      - name: Release

        run: |
          ./gradlew clean :swift-enums-core:release :swift-enums-processor:release :swift-enums-plugin:publishPluginMavenPublicationToGithubPackagesRepository