name: Release

on:
  push:
    branches:
      - develop

env:
  TOKEN: ${{ secrets.G_TOKEN }}

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Release
        env:
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.G_TOKEN }}
        run: |
          ./gradlew clean :swift-enums-core:publishAllPublicationsToGithubPackagesRepository :swift-enums-processor:publishAllPublicationsToGithubPackagesRepository :swift-enums-plugin:publishPluginMavenPublicationToGithubPackagesRepository